# Generated by Django 3.2.3 on 2021-05-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128)),
                ('mail', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
            ],
        ),
    ]
