# Generated by Django 3.2.3 on 2021-05-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='birth_date',
        ),
    ]
