# Generated by Django 3.2.3 on 2021-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_myuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='order_history',
            field=models.JSONField(null=True),
        ),
    ]
