# Generated by Django 3.2.3 on 2021-05-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_order_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cart',
            field=models.JSONField(null=True),
        ),
    ]
