# Generated by Django 3.2.3 on 2021-05-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_order_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='order_history',
            new_name='history',
        ),
    ]
