# Generated by Django 3.2.3 on 2021-05-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_order_history_myuser_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='history',
        ),
        migrations.AddField(
            model_name='myuser',
            name='order_history',
            field=models.JSONField(default=list),
        ),
    ]
