# Generated by Django 3.2.3 on 2021-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210518_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/itmo_tagline.png', null=True, upload_to=''),
        ),
    ]
