# Generated by Django 3.2.3 on 2021-05-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/itmo_tagline.png', null=True, upload_to='products/'),
        ),
    ]
